[theme]
primaryColor = "#2ecc71"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[server]
headless = true
runOnSave = true
maxUploadSize = 200
